### ISSUE TITLE
Sound design

### ISSUE THREAD

**Issue by LucasVinicius314** [Slashlust/slashlust#16]
Vou usar o  [freesound](https://freesound.org/ ) para pegar os sons. Mas tem que colocar os créditos dos autores assim que colocar.

Inicialmente vou colocar o som somente na parte do ataque do player, depois que os inimigos tiverem classe própria eu adiciono os sons de forma correta

**Comment by LucasVinicius314** [comment]
* Música
* Efeitos

**Comment by fariazinhu** [comment]
Fluxo:
- [Entrar no jogo e tocar uma música mais clássica (JOGO MEDIEVAL)](https://www.youtube.com/watch?v=t2rs-OyJ-Q8)
- Efeitos sonoros: 
    - [Espada geral](https://www.youtube.com/watch?v=2Yzn6PxIsGM)
    - [Espada se chocando](https://www.youtube.com/watch?v=iNlZIZDoCPY)
    - [Afiar de espada](https://www.youtube.com/watch?v=2nVMBMDS3_U)
    - [Golpe de espada](https://www.youtube.com/watch?v=rDzkm9xjusA)

**Comment by zTrolly** [comment]
> Member
